version: "3.8"
services:
  api1: &api1
    image: pablowinck/rinha-quarkus-reactive:2.6.9
    environment:
      DATABASE_URL: vertx-reactive:postgresql://db:5432/root?schema=public
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 2309
      SERVER_PORT: 3000
    expose:
      - 3000
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 500M

  api2:
    <<: *api1
    environment:
      DATABASE_URL: vertx-reactive:postgresql://db:5432/root?schema=public
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 2309
      SERVER_PORT: 3001
    expose:
      - 3001

  nginx: # Load Balancer
    image: pablowinck/custom-ngnix:1.6
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 500M

  db: # Banco de dados
    image: pablowinck/custom-postgres:1.2
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "2309"
      POSTGRES_DB: "root"
      PGDATA: /var/lib/postgresql/data/some_name/
    deploy:
      resources:
        limits:
          cpus: "0.9"
          memory: "1.5GB"

## 1.5 CPU
## 3 GB