version: "3.8"
services:
  api1: # API - Instância 01
    image: pablowinck/rinha-quarkus-reactive:1.4
    environment:
      DATABASE_URL: vertx-reactive:postgresql://db:5432/root?schema=public
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 2309
      SERVER_PORT: 3000
    depends_on:
      - db
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.3GB"

  api2: # API - Instância 02
    image: pablowinck/rinha-quarkus-reactive:1.4
    environment:
      DATABASE_URL: vertx-reactive:postgresql://db:5432/root?schema=public
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 2309
      SERVER_PORT: 3000
    depends_on:
      - db
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.3GB"

  nginx: # Load Balancer
    image: pablowinck/custom-ngnix:1.1
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.9GB"

  db: # Banco de dados
    image: pablowinck/custom-postgres:1.0
    ports:
      - "5432:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "2309"
      POSTGRES_DB: "root"
      PGDATA: /var/lib/postgresql/data/some_name/
    deploy:
      resources:
        limits:
          cpus: "0.9"
          memory: "1.5GB"
## 1.5 CPU
## 3 GB